openapi: 3.0.1
info:
  title: API PartyManagement
  description: ''
  version: 1.0-191114
  contact:
    name: Artem Ivlev
paths:
  /individual:
    get:
      tags:
        - individual
      summary: Поиск записи ФЛ
      operationId: individualFind
      parameters:
        - $ref: ../models/common/common.json#/components/parameters/offsetParam
        - $ref: ../models/common/common.json#/components/parameters/limitParam
        - $ref: ../models/common/common.json#/components/parameters/fieldsParam
        - $ref: ../models/common/common.json#/components/parameters/depthParam
        - $ref: ../models/common/common.json#/components/parameters/expandParam
        - $ref: ../models/common/common.json#/components/parameters/filterParam
      responses:
        '200':
          description: Список ФЛ
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/individual/Individual.v1.yaml
      deprecated: false
      description: Поиск явно не первый приоритет
    post:
      tags:
        - individual
      summary: Создание записи ФЛ
      operationId: individualCreate
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/individual/Individual.v1.yaml
        required: true
      responses:
        '201':
          description: Individual
          content:
            application/json:
              schema:
                $ref: ../models/individual/Individual.v1.yaml
      deprecated: false
      x-codegen-request-body-name: individual
    parameters: []
  '/individual/{individualId}':
    get:
      tags:
        - individual
      summary: Получение записи ФЛ
      operationId: individualGet
      parameters:
        - name: individualId
          in: path
          required: true
          schema:
            type: string
        - name: fields
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Individual
          content:
            application/json:
              schema:
                $ref: ../models/individual/Individual.v1.yaml
      deprecated: false
    put:
      tags:
        - individual
      summary: Обновление записи ФЛ
      operationId: individualUpdate
      parameters:
        - name: individualId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/individual/Individual.v1.yaml
        required: true
      responses:
        '201':
          description: Success Individual
          content:
            application/json:
              schema:
                $ref: ../models/individual/Individual.v1.yaml
      deprecated: false
      x-codegen-request-body-name: individual
    delete:
      tags:
        - individual
      summary: Логическое удаление записи ФЛ
      operationId: individualDelete
      parameters:
        - name: individualId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Success
          content: {}
      deprecated: false
    patch:
      tags:
        - individual
      summary: Частичное обновление записи ФЛ
      operationId: individualPatch
      parameters:
        - name: individualId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/individual/Individual.v1.yaml
        required: true
      responses:
        '200':
          description: Success Individual
          content:
            application/json:
              schema:
                $ref: ../models/individual/Individual.v1.yaml
      deprecated: false
      x-codegen-request-body-name: individual
    parameters:
      - schema:
          type: string
        name: individualId
        in: path
        required: true
  '/individual/{individualId}/document':
    get:
      tags:
        - document
      summary: Получение списка документов
      operationId: GetDocumentList
      parameters:
        - $ref: 'https://api.swaggerhub.com/domains/ArtemIvlev/common/1.0.0#/components/parameters/filterParam'
        - $ref: 'https://api.swaggerhub.com/domains/ArtemIvlev/common/1.0.0#/components/parameters/offsetParam'
        - $ref: 'https://api.swaggerhub.com/domains/ArtemIvlev/common/1.0.0#/components/parameters/limitParam'
        - $ref: 'https://api.swaggerhub.com/domains/ArtemIvlev/common/1.0.0#/components/parameters/fieldsParam'
        - $ref: 'https://api.swaggerhub.com/domains/ArtemIvlev/common/1.0.0#/components/parameters/depthParam'
        - $ref: 'https://api.swaggerhub.com/domains/ArtemIvlev/common/1.0.0#/components/parameters/expandParam'
      responses:
        '200':
          description: Список документов
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/docs/DocResponse.yaml
      deprecated: false
      description: 'Можно получить все документы или отфильтровать их по типу, по источнику и по дате актуальности и получить один'
    parameters:
      - schema:
          type: string
        name: individualId
        in: path
        required: true
